version: '3.8'

services:
  symfony:
    image: php:8.2-cli-alpine
    container_name: symfony-php
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
