controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_todos:
    path: /api/todos
    controller: App\Controller\TodoController::getTodos
    methods: GET
